channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - tensorflow-intel==2.16.1
  - tensorflow==2.18.0rc1
name: mlflow-env
